# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    page_prefix: reader

services:
    app.readerfactory:
        class: AppBundle\Service\ReaderServiceFactory
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@request_stack"]
    app.tblprefix_subscriber:
        class: AppBundle\Event\TablePrefixSubscriber
        arguments: [ "%page_prefix%" ]
        tags:
            - { name: doctrine.event_subscriber }
    app.readerservice:
        class: AppBundle\Service\ReaderService
        factory : ["@app.readerfactory", getService]



